spring:
  profiles:
    active: "@environment@"

  devtools:
    restart:
      enabled: true

  mvc:
    static-path-pattern: /static/**
  
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/public/
      add-mappings: true

hikari:
  minimum-idle: 3  # 最小空闲连接数量
  maximum-pool-size: 5  # 连接池最大连接数，默认是10
  max-lifetime: 1800000  # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
  connection-test-query: SELECT 1



# 基础访问路径
# server:
#   servlet:
#     # 排除静态资源
#     context-path: /api

mybatis:
  # 搜索指定包别名
  #typeAliasesPackage: com.wr.api.business.entity
  # typeAliasesPackage: com.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mappers/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

logging:
  charset:
    console: GBK


