server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/study
    username: root
    password: 010729lsr
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: 123123
      roles:
        - ADMIN
        - USER
  mail:
    host: smtp.163.com
    username: kucaisr@163.com
    password: KUgzWgTf4zcj2f3V
springdoc:
  api-docs:
    enabled: true