spring:
  profiles:
    active: "@environment@"

  devtools:
    restart:
      enabled: true

  # mvc:
    # static-path-pattern: 
      
  web:
    resources:
      # static-locations:
      #   - classpath:/static/
      #   - classpath:/META-INF/resources/
      #   - classpath:/resources/
      #   - classpath:/public/
      #   - file:./static/  # 添加这一行
      add-mappings: true

  # 文件上传
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      # 移除location配置，避免影响文件上传路径
      # location: ${user.dir}/sr-api/static/upload
    

# 基础访问路径
# server:
#   servlet:
#     # 排除静态资源
#     context-path: /api

mybatis:
  # 搜索指定包别名
  #typeAliasesPackage: com.wr.api.business.entity
  # typeAliasesPackage: com.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mappers/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

logging:
  charset:
    console: GBK

# 自定义全局配置
# 图片上传路径
file:
  # 默认上传文件保存路径改为相对路径
  upload: static/upload
  # 上传文件临时目录
  temp: /static/temp/
  # 上传文件大小限制
  maxSize: 10
  # 上传文件类型限制
  type: jpg,jpeg,png,gif,zip,rar,doc,docx,xls,xlsx,pdf,txt,md
  # 服务器域名
  domain: localhost
  # 服务器端口
  port: 8080

